server:
  port: 8080
spring:
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false

  redis:
    database: 0
    host: 192.168.53.178
    port: 6379
    password:
    timeout: 2000
    jedis:
      pool:
        max-active: 20
        max-wait: -1
        max-idle: 10
        min-idle: 0
    redisson:
      config: classpath:redisson.yaml

logging:
  level:
    org.springframework.data.mongodb.core: DEBUG    
